### ISSUE TITLE
EvenTheOdds - breaks campaign

### ISSUE THREAD

**Issue by Cat-Lady** [MadModsBattletech/BourbonVanillaEnhanced#2]
Hello Mad,
There is a critical bug with the "EvenTheOdds" part of your modpack. While it is in use, the "Capture the Argo" campaign mission gets stuck at the very end - Grym Sibil *does not* spawn in her Quickdraw (only her wingman in Shadowhawk spawns properly), keeping the mission forever stuck at 6/7 pirate reinforcements killed.

The bug is 100% reproducible every time and I've checked that just having this only mod enabled triggers it (just the same as using whole modpack or parts of it, together with EvenTheOdds). I can only guess, that it is some issue with the part that was supposed to spawn better equipped and trained AI pilots in the "named" instances of their appearance in campaign/career?

In any case, if you find time to look at it, could you also proof-check other campaign encounters? Those type of blockers are really throwing one out of the atmosphere (especially, if happening during a self-imposed ironman run with difficulty turned to max and all of you diff-raising fixes included).

thank you for your work on the tweaks,
/CatLady

**Comment by mad2342** [comment]
Hi Cat-Lady,
I just checked codewise and replayed the mentioned mission with no issues using the current release.
The only change to the encounter is an updated mechdef for the Quickdraw (which is existent and loading) and a change to better pilotdef for Grim Sybil (pilot_d4_defender -> pilot_d7_defender) which also works for me (pilot_d7_defender is a vanilla pilotdef).

Are you using ModTek? Any mods that modify the vanilla pilotdefs probably?

Best regards, Mad

**Comment by Cat-Lady** [comment]
Hey Mad,
This makes me really perplexed - the only mods that I am using are the ones listed in the other report:
https://github.com/MadModsBattletech/BourbonVanillaEnhanced/issues/1

...but I also tested with all except "EvenTheOdds" disabled *and* removed, and the result was same, 100% reproducible for me. Indeed, I am using ModTek - maybe it is not removing something correctly? In any case, I don't think any of the mods is was pilotdefs (most are from you, and the HyadesRim is just adding flashpoints, RimWardPeriphery planets, and CareerLeopardStart changes starting ship in career mode - nothing inside seems to be related). I was not using any other mods, neither on this install, or ever.

The only additional bit of info I can think of is that I'm using native Linux version of Battletech. If you have any ideas what to test on my side, I'll gladly do.

Cheers,
/CatLady

**Comment by mad2342** [comment]
I diffed the original contract json against my changes, it's only two lines changed for sure and as long as ModTek doesn't report errors with populating the DB with MechDef "mechdef_quickdraw_QKD-4G_P" the error should not be related to the contract changes.
The mentioned mission had (has?) some issues in vanilla itself, also related to unit-spawning and such, hopefully it's not just that still persisting.

A few ideas on what to check:

- Delete the file "\Mods\EvenTheOdds\StreamingAssets\data\contracts\story_3_axylus\Story_3_Axylus_Default.json and see if it works out. 

- I once had an issue with some mod, that *removed* some files in an update and i didn't delete/repopulate the mod, but copied the new contents over, overwriting. This resulted in some old, obsolete files interfering with the current state of the mod and throwing errors. -> Completely delete mod and apply current version from scratch

- Check the output_log.txt of the game for weirdnesses (location depends on OS so no idea where yours is located). Edit: https://forum.paradoxplaza.com/forum/threads/needed-support-logs-save-locations.1133621/

Hope sth helps, best regards, Mad
